title:              Austinia's Blog
email:              vladimir90919@gmail.com
description:        Blog with OpenSourceClass
author:             Austinia
baseurl:            "/blog"
url:                "https://austinia.github.io"

# Social Profiles
twitter_username:   
github_username:    austinia
facebook_username:  
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-157813108-1 # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
